### ISSUE TITLE
Remove trailing colons in example

### ISSUE THREAD

**Issue by behas** [marcelotto/skout#2]
When trying the given example as it is, I get the following error:

`** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): SPARQL.Query.Result, RDF.PrefixMap, RDF.List, RDF.Description, RDF.Dataset, RDF.Graph, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:1998: Enum.reduce_while/3
    (skout) lib/skout/yaml/decoder.ex:118: anonymous fn/3 in Skout.YAML.Decoder.build_skos/3
    (elixir) lib/enum.ex:3358: Enumerable.Map.reduce_list/3
    (elixir) lib/enum.ex:1998: Enum.reduce_while/3
    (skout) lib/skout/yaml/decoder.ex:139: anonymous fn/3 in Skout.YAML.Decoder.build_skos/3
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3`

Removing colons for concepts without narrower definitions solves the problem.

```
base: http://transport.data.gov.uk/def/vehicle-category/
concept_scheme:
  title: Vehicle Types
  creator: UK Department for Transport
  isDefinedBy: <http://www.dft.gov.uk/matrix/forms/definitions.aspx>
  seeAlso: <https://www.jenitennison.com/2009/11/22/creating-linked-data-part-iii-defining-concept-schemes.html>
iri_normalization: camelize  
---
- Pedal cycles
- All motor vehicles:
  - Two wheeled motor vehicles
  - Cars and taxis
  - Buses and coaches
  - Light vans
  - All HGV:
    - Rigid HGV:
      - HGVr2
      - HGVr3
      - HGVr4+
    - Articulated HGV:
      - HGVa3/4
      - HGVa5
      - HGVa6

```

**Comment by marcelotto** [comment]
Thanks.
